"""
Alert trigger system for the Smart City Platform.
Manages alerts generated by DFA state transitions.
"""
from __future__ import annotations
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Dict, List, Optional


class AlertSeverity(Enum):
    """Alert severity levels."""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


@dataclass
class Alert:
    """Represents a platform alert."""
    id: str
    type: str
    severity: AlertSeverity
    message: str
    entity_id: int
    entity_type: str
    timestamp: datetime
    resolved: bool = False
    resolved_at: Optional[datetime] = None

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "type": self.type,
            "severity": self.severity.value,
            "message": self.message,
            "entity_id": self.entity_id,
            "entity_type": self.entity_type,
            "timestamp": self.timestamp.isoformat(),
            "resolved": self.resolved,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
        }

    def __repr__(self) -> str:
        status = "RESOLVED" if self.resolved else "ACTIVE"
        return f"<Alert [{self.severity.value}] {self.type}: {self.message[:50]}... ({status})>"


class AlertManager:
    """
    Manages platform alerts from DFA transitions.

    Stores active/resolved alerts in memory.
    In production, alerts would be persisted to the database.

    Usage::
        manager = AlertManager()
        alert = manager.trigger_alert("SENSOR_DOWN", AlertSeverity.HIGH, "Sensor offline", 1, "Capteur")
        manager.resolve_alert(alert.id)
    """

    # Sensor downtime threshold before alert (hours)
    SENSOR_DOWNTIME_THRESHOLD_HOURS = 24
    # Intervention timeout per state (hours)
    INTERVENTION_TIMEOUT_HOURS = {
        "DEMAND": 24,
        "TECH1_ASSIGNED": 48,
        "TECH2_VALIDATED": 24,
        "AI_VALIDATED": 12,
    }
    # Vehicle route threshold (hours)
    VEHICLE_ROUTE_THRESHOLD_HOURS = 2

    def __init__(self) -> None:
        self._alerts: Dict[str, Alert] = {}

    # ------------------------------------------------------------------
    # Core operations
    # ------------------------------------------------------------------

    def trigger_alert(
        self,
        alert_type: str,
        severity: AlertSeverity,
        message: str,
        entity_id: int,
        entity_type: str,
    ) -> Alert:
        """Create and store a new alert."""
        alert = Alert(
            id=str(uuid.uuid4()),
            type=alert_type,
            severity=severity,
            message=message,
            entity_id=entity_id,
            entity_type=entity_type,
            timestamp=datetime.now(),
        )
        self._alerts[alert.id] = alert
        return alert

    def resolve_alert(self, alert_id: str) -> bool:
        """Mark an alert as resolved. Returns True if found."""
        alert = self._alerts.get(alert_id)
        if alert:
            alert.resolved = True
            alert.resolved_at = datetime.now()
            return True
        return False

    def get_active_alerts(self) -> List[Alert]:
        """Return all unresolved alerts sorted by severity (CRITICAL first)."""
        order = {AlertSeverity.CRITICAL: 0, AlertSeverity.HIGH: 1,
                 AlertSeverity.MEDIUM: 2, AlertSeverity.LOW: 3}
        return sorted(
            [a for a in self._alerts.values() if not a.resolved],
            key=lambda a: (order[a.severity], a.timestamp),
        )

    def get_all_alerts(self) -> List[Alert]:
        """Return all alerts."""
        return list(self._alerts.values())

    def get_alerts_by_entity(self, entity_id: int, entity_type: str) -> List[Alert]:
        """Return alerts for a specific entity."""
        return [
            a for a in self._alerts.values()
            if a.entity_id == entity_id and a.entity_type == entity_type
        ]

    def clear_resolved(self) -> int:
        """Remove resolved alerts from memory. Returns count removed."""
        resolved_ids = [k for k, v in self._alerts.items() if v.resolved]
        for aid in resolved_ids:
            del self._alerts[aid]
        return len(resolved_ids)

    # ------------------------------------------------------------------
    # Domain-specific alert checks
    # ------------------------------------------------------------------

    def check_sensor_downtime(
        self,
        sensor_id: int,
        last_transition_time: datetime,
    ) -> Optional[Alert]:
        """
        Check if a sensor has been down for more than SENSOR_DOWNTIME_THRESHOLD_HOURS.
        Returns a new Alert if threshold exceeded, else None.
        """
        downtime = datetime.now() - last_transition_time
        if downtime > timedelta(hours=self.SENSOR_DOWNTIME_THRESHOLD_HOURS):
            return self.trigger_alert(
                alert_type="SENSOR_DOWNTIME",
                severity=AlertSeverity.HIGH,
                message=(
                    f"Sensor {sensor_id} has been offline for "
                    f"{int(downtime.total_seconds() // 3600)} hours"
                ),
                entity_id=sensor_id,
                entity_type="Capteur",
            )
        return None

    def check_intervention_timeout(
        self,
        intervention_id: int,
        creation_time: datetime,
        state: str,
    ) -> Optional[Alert]:
        """
        Check if an intervention has been in given state too long.
        Returns a new Alert if timeout exceeded, else None.
        """
        threshold_hours = self.INTERVENTION_TIMEOUT_HOURS.get(state)
        if threshold_hours is None:
            return None
        elapsed = datetime.now() - creation_time
        if elapsed > timedelta(hours=threshold_hours):
            severity = AlertSeverity.CRITICAL if threshold_hours <= 12 else AlertSeverity.HIGH
            return self.trigger_alert(
                alert_type="INTERVENTION_TIMEOUT",
                severity=severity,
                message=(
                    f"Intervention {intervention_id} stuck in state {state!r} "
                    f"for {int(elapsed.total_seconds() // 3600)} hours "
                    f"(limit: {threshold_hours}h)"
                ),
                entity_id=intervention_id,
                entity_type="Intervention",
            )
        return None

    def check_vehicle_route_time(
        self,
        vehicle_id: int,
        depart_time: datetime,
    ) -> Optional[Alert]:
        """
        Check if a vehicle has been en route longer than threshold.
        Returns a new Alert if threshold exceeded, else None.
        """
        elapsed = datetime.now() - depart_time
        if elapsed > timedelta(hours=self.VEHICLE_ROUTE_THRESHOLD_HOURS):
            return self.trigger_alert(
                alert_type="VEHICLE_LONG_ROUTE",
                severity=AlertSeverity.MEDIUM,
                message=(
                    f"Vehicle {vehicle_id} has been en route for "
                    f"{int(elapsed.total_seconds() // 3600)} hours"
                ),
                entity_id=vehicle_id,
                entity_type="Vehicule",
            )
        return None

    def get_summary(self) -> dict:
        """Return alert summary statistics."""
        active = self.get_active_alerts()
        return {
            "total": len(self._alerts),
            "active": len(active),
            "resolved": len(self._alerts) - len(active),
            "by_severity": {
                sev.value: sum(1 for a in active if a.severity == sev)
                for sev in AlertSeverity
            },
        }

    def __repr__(self) -> str:
        return f"<AlertManager active={len(self.get_active_alerts())} total={len(self._alerts)}>"
