"""
AI report generator for the Smart City Platform.
Uses LangChain/OpenAI when available; falls back to template-based reports.
"""
from __future__ import annotations
import os
from datetime import datetime
from typing import Any, Optional


class ReportGenerator:
    """
    Generates analytical reports for the Smart City Platform.

    When an OpenAI API key is configured and use_openai=True, uses
    LangChain + GPT to generate rich natural-language reports.
    Otherwise, uses built-in template-based fallbacks that work
    without any API key or internet connection.

    Usage::
        gen = ReportGenerator(use_openai=False)
        report = gen.generate_city_dashboard_report({"active_sensors": 42})
    """

    # ------------------------------------------------------------------
    # Templates for fallback mode
    # ------------------------------------------------------------------

    _AIR_QUALITY_TEMPLATE = """
## Air Quality Report — {zone_name}
**Generated:** {timestamp}

### Current Status
- **Zone:** {zone_name}
- **Pollution Index:** {pollution_index:.1f} / 100
- **Air Quality Level:** {aqi_label}
- **Dominant Pollutant:** {dominant_pollutant}

### Analysis
{analysis}

### Recommendations
{recommendations}

---
*Report generated by Smart City Platform AI — Neo-Sousse 2030*
"""

    _MAINTENANCE_TEMPLATE = """
## Maintenance Report
**Generated:** {timestamp}

### Sensor Fleet Overview
- **Total Sensors Analysed:** {total_sensors}
- **Sensors Requiring Attention:** {sensors_needing_maintenance}
- **Critical Issues:** {critical_count}

### Prioritised Actions
{actions}

### Predicted Failures (Next 30 Days)
{predictions}

---
*Report generated by Smart City Platform AI — Neo-Sousse 2030*
"""

    _INTERVENTION_TEMPLATE = """
## Intervention Summary Report
**Generated:** {timestamp}

### Period Overview
- **Total Interventions:** {total}
- **Completed:** {completed}
- **Pending:** {pending}
- **AI Validated:** {ai_validated}

### Priority Breakdown
{priority_breakdown}

### Key Findings
{findings}

### Recommendations
{recommendations}

---
*Report generated by Smart City Platform AI — Neo-Sousse 2030*
"""

    _CITY_DASHBOARD_TEMPLATE = """
## City Health Dashboard Report — Neo-Sousse 2030
**Generated:** {timestamp}

### Executive Summary
{summary}

### Key Performance Indicators
| Metric | Value | Status |
|--------|-------|--------|
| Active Sensors | {active_sensors} | {sensors_status} |
| Pending Interventions | {interventions_pending} | {interventions_status} |
| Average Air Quality | {avg_pollution:.1f} AQI | {pollution_status} |
| Registered Citizens | {citizens} | ✅ |

### Environmental Health
{env_health}

### Infrastructure Status
{infra_status}

### Citizen Engagement
{citizen_engagement}

### Priority Actions
{priority_actions}

---
*Report generated by Smart City Platform AI — Neo-Sousse 2030*
"""

    def __init__(self, use_openai: bool = False) -> None:
        self.use_openai = use_openai
        self._llm: Optional[Any] = None
        self._reports_history: list[dict] = []

        if use_openai:
            self._init_llm()

    # ------------------------------------------------------------------
    # LLM initialisation
    # ------------------------------------------------------------------

    def _init_llm(self) -> None:
        """Attempt to initialise OpenAI LLM via LangChain."""
        api_key = os.getenv("OPENAI_API_KEY", "")
        if not api_key or api_key == "your_openai_api_key_here":
            self.use_openai = False
            return
        try:
            from langchain_openai import ChatOpenAI
            self._llm = ChatOpenAI(
                model="gpt-3.5-turbo",
                temperature=0.3,
                openai_api_key=api_key,
            )
        except ImportError:
            self.use_openai = False

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_air_quality_report(self, zone_data: dict) -> str:
        """Generate a textual air quality analysis for a zone."""
        if self.use_openai and self._llm:
            prompt = self._format_prompt(
                "Analyse the air quality data for zone {zone_name} "
                "with pollution index {pollution_index}. "
                "Provide recommendations for improving air quality. "
                "Data: {data}",
                zone_data,
            )
            return self._call_llm(prompt)
        return self._fallback_air_quality_report(zone_data)

    def generate_maintenance_report(self, sensor_data: list) -> str:
        """Generate maintenance recommendations from sensor data."""
        if self.use_openai and self._llm:
            prompt = self._format_prompt(
                "Analyse the following sensor data and provide a maintenance "
                "report with prioritised actions: {data}",
                {"data": str(sensor_data[:10])},
            )
            return self._call_llm(prompt)
        return self._fallback_maintenance_report(sensor_data)

    def generate_intervention_summary(self, intervention_data: list) -> str:
        """Summarise a list of interventions."""
        if self.use_openai and self._llm:
            prompt = self._format_prompt(
                "Summarise the following city interventions and provide "
                "key findings and recommendations: {data}",
                {"data": str(intervention_data[:20])},
            )
            return self._call_llm(prompt)
        return self._fallback_intervention_summary(intervention_data)

    def generate_city_dashboard_report(self, metrics: dict) -> str:
        """Generate an overall city health report from KPI metrics."""
        if self.use_openai and self._llm:
            prompt = self._format_prompt(
                "Generate a comprehensive city health report for Neo-Sousse 2030 "
                "based on the following metrics: {data}. "
                "Include executive summary, analysis, and recommendations.",
                {"data": str(metrics)},
            )
            return self._call_llm(prompt)
        return self._fallback_city_report(metrics)

    # ------------------------------------------------------------------
    # LLM call
    # ------------------------------------------------------------------

    def _call_llm(self, prompt: str) -> str:
        """Call LLM and return response text."""
        try:
            from langchain_core.messages import HumanMessage
            response = self._llm.invoke([HumanMessage(content=prompt)])
            text = response.content if hasattr(response, "content") else str(response)
            self._store_report(prompt, text)
            return text
        except Exception as exc:
            return f"[LLM unavailable: {exc}]\n\n" + self._fallback_report("generic", {})

    # ------------------------------------------------------------------
    # Fallback report generators (no API needed)
    # ------------------------------------------------------------------

    def _fallback_air_quality_report(self, data: dict) -> str:
        zone_name = data.get("zone_name", data.get("nom_zone", "Unknown Zone"))
        pollution = float(data.get("pollution_index", data.get("indice_pollution", 50)))
        
        if pollution < 20:
            label, dominant, analysis, recommendations = (
                "🟢 Excellent", "None significant",
                "Air quality in this zone is excellent. Pollution levels are well below safe thresholds.",
                "- Continue monitoring\n- Maintain green space coverage\n- Encourage cycling and walking",
            )
        elif pollution < 50:
            label, dominant, analysis, recommendations = (
                "🟡 Moderate", "Traffic emissions",
                "Air quality is acceptable but shows moderate pollution. Some sensitive groups may be affected.",
                "- Increase monitoring frequency\n- Promote public transport\n- Add green barriers near roads",
            )
        elif pollution < 75:
            label, dominant, analysis, recommendations = (
                "🟠 Poor", "Industrial/traffic",
                "Air quality is poor and may affect health for extended exposure. Action recommended.",
                "- Issue public health advisory\n- Restrict heavy vehicle traffic\n- Inspect industrial facilities",
            )
        else:
            label, dominant, analysis, recommendations = (
                "🔴 Hazardous", "Industrial pollution",
                "CRITICAL: Air quality is hazardous. Immediate action required.",
                "- Issue emergency health advisory\n- Suspend industrial operations\n- Deploy mobile monitoring",
            )

        report = self._AIR_QUALITY_TEMPLATE.format(
            zone_name=zone_name,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
            pollution_index=pollution,
            aqi_label=label,
            dominant_pollutant=dominant,
            analysis=analysis,
            recommendations=recommendations,
        )
        self._store_report("air_quality", {"zone": zone_name, "pollution": pollution})
        return report.strip()

    def _fallback_maintenance_report(self, sensor_data: list) -> str:
        total = len(sensor_data)
        faulty = sum(1 for s in sensor_data if isinstance(s, dict) and s.get("statut") in ("FAULTY", "MAINTENANCE"))
        critical = sum(1 for s in sensor_data if isinstance(s, dict) and s.get("etat_dfa") == "OUT_OF_SERVICE")
        
        actions = []
        for i, s in enumerate(sensor_data[:5], 1):
            if isinstance(s, dict):
                sid = s.get("id_capteur", i)
                stype = s.get("type_capteur", "Unknown")
                actions.append(f"{i}. Sensor #{sid} ({stype}): Schedule preventive inspection")
        if not actions:
            actions = ["1. Conduct routine sensor calibration", "2. Check battery levels on all sensors"]
        
        predictions = (
            f"- {max(1, faulty)} sensors predicted to require maintenance in next 30 days\n"
            f"- Estimated downtime: {faulty * 4} hours\n"
            f"- Recommended spare parts: {critical} replacement units"
        )

        report = self._MAINTENANCE_TEMPLATE.format(
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
            total_sensors=total,
            sensors_needing_maintenance=faulty,
            critical_count=critical,
            actions="\n".join(actions) or "No immediate actions required",
            predictions=predictions,
        )
        self._store_report("maintenance", {"total": total, "faulty": faulty})
        return report.strip()

    def _fallback_intervention_summary(self, intervention_data: list) -> str:
        total = len(intervention_data)
        if not total:
            return "No intervention data available."
        
        completed = sum(1 for i in intervention_data if isinstance(i, dict) and i.get("etat_dfa") == "COMPLETED")
        ai_validated = sum(1 for i in intervention_data if isinstance(i, dict) and i.get("valide_ia"))
        pending = total - completed
        
        priorities = {}
        for item in intervention_data:
            if isinstance(item, dict):
                p = item.get("priorite", "MEDIUM")
                priorities[p] = priorities.get(p, 0) + 1
        
        priority_lines = "\n".join(f"- {k}: {v}" for k, v in sorted(priorities.items()))
        
        findings = (
            f"- Completion rate: {completed/total*100:.1f}%\n"
            f"- AI validation rate: {ai_validated/total*100:.1f}%\n"
            f"- Average pending interventions: {pending}"
        )
        
        recommendations = (
            "- Increase technician availability for high-priority interventions\n"
            "- Automate AI validation for routine maintenance\n"
            "- Review sensor placement to reduce fault frequency"
        )

        report = self._INTERVENTION_TEMPLATE.format(
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
            total=total,
            completed=completed,
            pending=pending,
            ai_validated=ai_validated,
            priority_breakdown=priority_lines or "No priority data",
            findings=findings,
            recommendations=recommendations,
        )
        self._store_report("interventions", {"total": total, "completed": completed})
        return report.strip()

    def _fallback_city_report(self, metrics: dict) -> str:
        active_sensors = metrics.get("active_sensors", 0)
        pending = metrics.get("interventions_pending", 0)
        avg_pollution = float(metrics.get("avg_pollution", 50))
        citizens = metrics.get("citizens", 0)

        # Determine status labels
        sensors_status = "✅ Good" if active_sensors > 30 else "⚠️ Low"
        int_status = "✅ Manageable" if pending < 10 else ("⚠️ High" if pending < 20 else "🔴 Critical")
        poll_status = "✅ Good" if avg_pollution < 30 else ("⚠️ Moderate" if avg_pollution < 60 else "🔴 Poor")

        summary = (
            f"Neo-Sousse 2030 is operating with {active_sensors} active sensors across the city. "
            f"Current air quality average is {'good' if avg_pollution < 30 else 'moderate' if avg_pollution < 60 else 'poor'} "
            f"at {avg_pollution:.1f} AQI. "
            f"There are {pending} pending interventions requiring attention."
        )

        env_health = (
            f"- Average Pollution Index: {avg_pollution:.1f}/100\n"
            f"- Sensors Monitoring: {active_sensors}\n"
            f"- Air Quality Rating: {'Acceptable' if avg_pollution < 50 else 'Needs Improvement'}"
        )

        infra_status = (
            f"- Active IoT Sensors: {active_sensors}\n"
            f"- Pending Maintenance: {pending} interventions\n"
            f"- System Uptime: {'High' if active_sensors > 30 else 'Moderate'}"
        )

        citizen_engagement = (
            f"- Registered Citizens: {citizens}\n"
            f"- Ecological Score Average: {metrics.get('avg_ecological_score', 65):.1f}/100\n"
            f"- Active Consultations: {metrics.get('consultations', 0)}"
        )

        priority_actions = (
            "1. " + ("✅ Sensor network healthy" if active_sensors > 30 else "⚠️ Deploy additional sensors") + "\n"
            "2. " + ("✅ Interventions under control" if pending < 10 else "🔴 Reduce intervention backlog") + "\n"
            "3. " + ("✅ Air quality acceptable" if avg_pollution < 50 else "⚠️ Investigate pollution sources") + "\n"
            "4. Increase citizen engagement through mobile app notifications"
        )

        report = self._CITY_DASHBOARD_TEMPLATE.format(
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M"),
            summary=summary,
            active_sensors=active_sensors,
            sensors_status=sensors_status,
            interventions_pending=pending,
            interventions_status=int_status,
            avg_pollution=avg_pollution,
            pollution_status=poll_status,
            citizens=citizens,
            env_health=env_health,
            infra_status=infra_status,
            citizen_engagement=citizen_engagement,
            priority_actions=priority_actions,
        )
        self._store_report("city_dashboard", metrics)
        return report.strip()

    def _fallback_report(self, data_type: str, data: dict) -> str:
        """Generic fallback for unsupported report types."""
        return (
            f"## {data_type.replace('_', ' ').title()} Report\n"
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n"
            f"Template report generated for: {data_type}\n"
            f"Data summary: {str(data)[:200]}"
        )

    # ------------------------------------------------------------------
    # Prompt formatting
    # ------------------------------------------------------------------

    def _format_prompt(self, template: str, data: dict) -> str:
        """Format a prompt template with data."""
        try:
            return template.format(data=str(data), **data)
        except KeyError:
            return template.format(data=str(data))

    # ------------------------------------------------------------------
    # Report history
    # ------------------------------------------------------------------

    def _store_report(self, report_type: str, data: dict) -> None:
        self._reports_history.append({
            "type": report_type,
            "timestamp": datetime.now().isoformat(),
            "data_summary": str(data)[:100],
        })

    def get_report_history(self) -> list[dict]:
        """Return list of previously generated report metadata."""
        return list(self._reports_history)

    def __repr__(self) -> str:
        mode = "OpenAI" if (self.use_openai and self._llm) else "Template"
        return f"<ReportGenerator mode={mode!r} reports={len(self._reports_history)}>"
